server:
  port: 8186
  servlet:
    context-path: /
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=users
    username: postgres
    password: ${dbPassword}
  jackson:
    serialization:
      indent_output: true
